FROM python:3.8-slim

#RUN adduser --disabled-password --gecos '' netdiag

#WORKDIR /home/netdiag

RUN apt update && apt upgrade && apt install wget -y

WORKDIR /usr/src/app

#RUN python -m venv venv
RUN wget https://github.com/cbabs/netDiag/raw/master/Server/wsServer.py
RUN wget https://github.com/cbabs/netDiag/raw/master/Server/requirements-wss.txt
RUN pip install -r /usr/src/app/requirements-wss.txt

#RUN chown -R netdiag:netdiag ./
#USER netdiag

EXPOSE 8765
CMD [ "python", "/usr/src/app/wsServer.py" ]
