FROM python:3.8-slim

RUN adduser -D netdiag

WORKDIR /home/netdiag

RUN apk update && apk upgrade && \
    apk add --no-cache git

RUN python -m venv venv
RUN https://github.com/cbabs/netDiag/raw/master/Server/wsServer.py
RUN venv/bin/pip install -r ./netDiag/Server/requirements-wss.txt

RUN chown -R netdiag:netdiag ./
USER netdiag

EXPOSE 8765
ENTRYPOINT ["python ./netDiag/Server/wsServer.py"]

